### PR TITLE
Esp32 update for esp-idf v4.1

### PR DESCRIPTION
**Pull request by mathiasbredholt**
Just an update for the Esp32 port, using the new esp_netif API. This should allow to use Link with Esp32 with both STA, SoftAP, and Ethernet.

### CODE REVIEW

**Comment by fgo-ableton** [comment]
Let's stick with stable releases of esp-idf. I assume this is not part of [4.0](https://github.com/espressif/esp-idf/releases/tag/v4.0), as CI for 4.0-rc fails. We should update to 4.0 though.

**Comment by mathiasbredholt** [comment]
Agreed, it was mostly intended for a future release :)

**Comment by mathiasbredholt** [comment]
@fgo-ableton I've updated the pull request and with travis configuration set to ESP-IDF v4.1.

**Comment by mathiasbredholt** [comment]
@fgo-ableton Whoops, I see I forgot to check if the interface is active. I'll fix it and update the PR tomorrow :)

**Comment by mathiasbredholt** [comment]
Added interface up-check. PR should be ready now.

**Pull request merged**
