### PR TITLE
Add JACK timebase support to example applications.

### PR DESCRIPTION
**Pull request by rncbc**
Add JACK Timebase master support to example applications, updating extended BBT (bar.beat.tick) position and BPM (tempo) information, as read from Link and proposed as an one-way bridge to JACK Transport interface.

### CODE REVIEW

**Comment by fgo-ableton** [comment]
Sorry for the late reply and thanks for the PR.
I like the idea of having a conversion from Link to jack timebase. Unfortunately I think it does not make sense to be part of the example applications.
What about making a more general adapter, (without the metronome sound), use this repo as a submodule and host it on your site? Here's an example of a project doing something similar: https://github.com/brunchboy/carabiner

**Comment by rncbc** [comment]
got it. thanks.

in a way, i've made myself an alpha prototype for a so called _full duplex_ JACK/Link transport/timebase bridge, meaning both ways this time, and it's there now for your (peer) review ...

give and take, it's in alpha stage, so that I might rehash it anytime, any other day or night, but most importantly, I will take any feedback into account, nevertheless ;)

https://github.com/rncbc/jack_link

**Comment by abique** [comment]
Hi @rncbc I would suggest to squash your commits.

**Comment by rncbc** [comment]
hi @abique, might not be necessary: this PR is not to be merged anytime soon, most probably is to be closed any of these days...

this PR has been superseded by https://github.com/rncbc/jack_link , also as per @fgo-ableton suggestion.

**Comment by rncbc** [comment]
@abique, anyway, commits squashed now.
thanks

**Comment by abique** [comment]
Thank you :+1:

**Pull request closed without merging**
