### PR TITLE
Simplify the source code in order to compile with clang-cl.exe 10.0

### PR DESCRIPTION
**Pull request by abique**
Inheriting std::tuple<> made the code complex and led to compilation
error when doing std::get<0>(*this);

### CODE REVIEW

**Comment by cdi-ableton** [comment]
Thanks for the changes, @abique!
Could you please squash 9b2bc494413cb5382a2b957af48cf11ca32a6e93 and fbe88e88c7811a886b95fa677cbcb6c2d447a2e8 into 2a8695405ba660f7fe0f6e30213a32f84bcfb856 since they remove code that was added with the initial commit of this branch. If you want to convey information about the issues with VS2015 feel free to put them into the commit message.

**Comment by abique** [comment]
Yes of-course I will squash it tonight.

**Comment by abique** [comment]
I've done the re-base and squashed the commits.

Thank you for taking the time to review the change.

**Comment by cdi-ableton** [comment]
Thanks for squashing! I think there was a little misunderstanding. I'd like to have one commit that updates `asio` and one that introduces the code changes.

**Comment by abique** [comment]
Done.

**Pull request merged**
