### PR TITLE
build support for Debian/kFreeBSD and Deian/HURD

### PR DESCRIPTION
**Pull request by umlaeute**
This PR allows me to build *link* on **Debian/kFreeBSD** and **Debian/GNU Hurd**.

The changes are rather non-invasive:
- in the CMakeFiles treat `kFreeBSD` and `GNU` systems the same as `Linux` (after all: they *are* very similar)
- since *FreeBSD* does not have `CLOCK_MONOTONIC_RAW` defined, we fall back to `CLOCK_MONOTONIC` on this system.

Closes: https://github.com/Ableton/link/issues/19

### CODE REVIEW

**Comment by fgo-ableton** [comment]
Thanks a lot!
Looks good to me.
Could you please sign a CLA so we can merge this: https://ableton.github.io/cla/

**Comment by umlaeute** [comment]
consider my changes to be in the public domain.

**Comment by fgo-ableton** [comment]
I understand this might seem a litte overkill for a small build system change.
However, the CLA is necessary for any contribution so that we can legally make use of the changes ourselves - and it does not do anything besides that.
I'd appreciate if you could submit it. (It does not require to print and mail anything). I'm afraid I won't be able to merge otherwise.
Thanks a lot!

**Comment by fgo-ableton** [comment]
Thanks a lot!

**Pull request merged**
